name: fantesia
description: Client Jellyfin dedie au serveur Fantesia.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  webview_flutter: ^4.10.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  device_info_plus: ^10.1.2
  wakelock_plus: ^1.2.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
